config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get "/auth/:provider/callback" => "sessions#create"
  delete "/logout" => "sessions#destroy", as: :logout

  resource :retirements, only: %i[new create]

  resources :events, only: %i[new create show edit update destroy] do
    resources :tickets, only: %i[new create destroy]
  end

  get 'status' => 'status#index', defaults: { format: 'json' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :image, dependent: false
  has_many :tickets, dependent: :destroy
  belongs_to :owner, class_name: "User"

  validates :image,
    content_type: [:png, :jpg, :jpeg],
    size: { less_than_or_equal_to: 10.megabytes },
    dimension: { width: { max: 2000 }, height: { max: 2000 } }

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validate :start_at_should_be_before_end_at

  attr_accessor :remove_image

  before_save :remove_image_if_user_accept

  def created_by?(user)
    return false unless user
    # 上の文の代わりにぼっち演算子でもいい？
    owner_id == user.id
  end

  private

  def start_at_should_be_before_end_at
    return unless start_at && end_at

    if start_at >= end_at
      errors.add(:start_at, "は終了時間よりも前に設定してください")
    end
  end

  def remove_image_if_user_accept
    self.image = nil if ActiveRecord::Type::Boolean.new.cast(remove_image)
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event

  validates :comment, length: { maximum: 30 }, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :check_all_events_finished

  has_many :created_events, class_name: "Event", foreign_key: "owner_id", dependent: :nullify

  has_many :tickets, dependent: :nullify
  has_many :participating_events, through: :tickets, source: :event

  def self.find_or_create_from_auth_hash!(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by!(provider: provider, uid: uid) do |user|
      user.name = nickname
      user.image_url = image_url
    end
  end

  private

  def check_all_events_finished
    now = Time.zone.now
    if created_events.where(":now < ent_at", now: now).exists?
      errors[:base] << "公開中の未終了イベントが存在します。"
    end

    if participating_events.where(":now < end_at", now: now).exists?
      errors[:base] << "未終了の参加イベントが存在します。"
    end

    throw(:abort) unless errors.empty?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate
  helper_method :logged_in?, :current_user

  private

  def logged_in?
    !!current_user
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: "ログインしてください"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate, only: :show

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event, notice: "作成しました"
    end
  end

  def show
    @event = Event.find(params[:id])
    @ticket = current_user && current_user.tickets.find_by(event: @event)
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def edit
    @event = current_user.created_events.find(params[:id])
  end

  def update
    @event = current_user.created_events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "更新しました"
    end
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.destroy!
    redirect_to root_path, notice: "削除しました"
  end

  private

  def event_params
    params.require(:event).permit(
      :name, :place, :content, :start_at, :end_at, :image, :remove_image
    )
  end
end

app/controllers/retirements_controller.rb
class RetirementsController < ApplicationController
  def new
  end

  def create
    if current_user.destroy
      reset_session
      redirect_to root_path, notice: "退会完了しました"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: :create

  def create
    user = User.find_or_create_from_auth_hash!(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path, notice: "ログインしました"
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "ログアウトしました"
  end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  skip_before_action :authenticate
  def index
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    raise ActionController::RoutingError, "ログイン状態で TicketsController#newにアクセス"
  end

  def create
    event = Event.find(params[:event_id])
    @ticket = current_user.tickets.build do |t|
      t.event = event
      t.comment = params[:ticket][:comment]
    end
    if @ticket.save
      redirect_to event, notice: "このイベントに参加表明しました"
    end
  end

  def destroy
    ticket = current_user.tickets.find_by!(event_id: params[:event_id])
    ticket.destroy!
    redirect_to event_path(params[:event_id]), notice: "このイベントの参加をキャンセルしました"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate

  def index
    @events = Event.page(params[:page]).per(10)
      .where("start_at > ?", Time.zone.now).order(:start_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_for_github(user)
    "https://github.com/#{user.name}"
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/retirements_helper.rb
module RetirementsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_errors.html.haml
.alert.alert-danger
  %ul.mb-0
    - errors.full_messages.each do |message|
      %li= message

app/views/events/create.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @event.errors) %>"

app/views/events/edit.html.haml
- now = Time.zone.now

%h1.mt-2 イベント情報編集

= form_with(model: @event, class: "form-horizontal") do |f|
  #errors
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :place
    = f.text_field :place, class: "form-control"
  .form-group
    = f.label :start_at
    %div
      = f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :end_at
    %div
      = f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :content
    = f.text_area :content, class: "form-control", row: 10
  .form-group
    = f.label :image
    - if @event.image.attached? && @event.image.blob&.persisted?
      = image_tag(@event.image.variant(resize_to_fit: [200, 200]), class: 'img-tumbnail d-block mb-3')
    = f.file_field :image, class: "form-control-file"
  - if @event.image.attached? && @event.image.blob&.persisted?
    .check-box
      %label
        = f.check_box :remove_image
        画像を削除する
  = f.submit class: "btn btn-primary"

app/views/events/new.html.haml
- now = Time.zone.now

%h1.mt-2 イベント作成

= form_with(model: @event,local: false, class: "form-horizontal") do |f|
  #errors
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :place
    = f.text_field :place, class: "form-control"
  .form-group
    = f.label :start_at
    %div
      = f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :end_at
    %div
      = f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :content
    = f.text_area :content, class: "form-control", row: 10
  .form-group
    = f.label :image
    = f.file_field :image, class: "form-control-file"
  = f.submit class: "btn btn-primary"

app/views/events/show.html.haml
%h1.mt-3.mb-3= @event.name
.row
  .col-8
    .card.mb-2
      - if @event.image.attached?
        = image_tag @event.image, class: "card-img-top"
    .card.mb-2
      %h5.card-header イベント内容
      .card-body
        %p.card-text= @event.content
    .card.mb-2
      %h5.card-header 開催時間
      .card-body
        %p.card-text= "#{l(@event.start_at, format: :long)} - #{l(@event.end_at, format: :long)}"
    .card.mb-2
      %h5.card-header 開催場所
      .card-body
        %p.card-text= @event.place
    .card.mb-2
      %h5.card-header 主催者
      .card-body
        -if @event.owner
          = link_to(url_for_github(@event.owner), class: "card-link") do
            = image_tag @event.owner.image_url, width: 50, height: 50
            = "@#{@event.owner.name}"
        - else
          退会したユーザです
  .col-4
    - if @event.created_by?(current_user)
      = link_to "イベントを編集する", edit_event_path(@event), class: "btn btn-info btn-lg btn-block"
      = link_to "イベントを削除する", event_path(@event), class: "btn btn-danger btn-lg btn-block", method: :delete, data: { confirm: "本当に削除しますか？" }
    - if @ticket
      = link_to "参加をキャンセルする", event_ticket_path(@event, @ticket), method: :delete, class: "btn btn-warning btn-lg btn-block"
    - elsif logged_in?
      %button.btn.btn-primary.btn-lg.btn-block{ "data-toggle" => "modal", "data-target" => "#createTicket" }
        参加する
      %div.modal.fade#createTicket
        .modal-dialog
          .modal-content
            .modal-header
              %h4.modal-title#dialogHeader 参加コメント
              %button.close{ type: "button", "data-dismiss" => "modal" } &times;
            = form_with(model: @event.tickets.build, url: event_tickets_path(@event), local: false) do |f|
              .modal-body
                #createTicketErrors
                = f.text_field :comment, class: "form-control"
              .modal-footer
                %button.btn.btn-default{ type: "button", "data-dismiss" => "modal" }
                  キャンセル
                = f.button "送信", class: "btn btn-primary"
    - else
      = link_to "参加する", new_event_ticket_path(@event), class: "btn btn-primary btn-lg btn-block"
    %hr
    .card.mb-2
      %h5.card-group.list-group-flush
        - @tickets.each do |ticket|
          %li.list-group-item
            -if ticket.user
              = link_to(url_for_github(ticket.user), class: "card-link") do
                = image_tag ticket.user.image_url, width: 20, height: 20
                = "@#{ticket.user.name}"
              = ticket.comment
            - else
              退会したユーザです

app/views/events/update.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @event.errors) %>"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title AwesomeEvents
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header.navbar.navbar-expand-sm.navbar-light.bg-light
      .container
        = link_to "AwesomeEvents", root_path, class: "navbar-brand mr-auto"
        %ul.navbar-nav
          %li.nav-item
            = link_to "イベントを作る", new_event_path, class: "nav-link"
          - if logged_in?
            %li.nav-item
              = link_to "退会", new_retirements_path, class: "nav-link"
            %li.nav-item
              = link_to "ログアウト", logout_path, class: "nav-link", method: :delete
          - else
            %li.nav-item
              = link_to "GitHubでログイン", "/auth/github", class: "nav-link", method: :post
    .container
      - if flash.notice
        .alert.alert-success
          = flash.notice
      - if flash.alert
        .alert.alert-danger
          = flash.alert
      = yield

app/views/retirements/create.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: current_user.errors) %>"

app/views/retirements/new.html.haml
%h1.mt-3 退会の確認

#errors 

%p 退会した場合、ユーザに関するデータが全て削除されます。
%p ただし、以下の場合は退会できません。

%ul
  %li
    公開中の未終了イベントがある場合
  %li
    未終了の参加イベントがある場合
%hr

= link_to "退会する", retirements_path, method: :post, remote: true, class: "btn btn-danger", data: { confirm: "本当に退会しますか？" }

app/views/tickets/create.js.erb
document.getElementById("createTicketErrors").innerHTML = "<%= j render("errors", errors: @ticket.errors) %>"

app/views/welcome/index.html.haml
%h1 イベント一覧

%ul.list-group
  - @events.each do |event|
    = link_to(event, class: "list-group-item list-group-item-action") do
      %h5.list-group-item-heading= event.name
      %p.mb-1= "#{l(event.start_at, format: :long)} - #{l(event.end_at, format: :long)}"

= paginate @events